# Docker Compose para Sistema de Manutenção Preditiva
# Bootcamp CDIA - Projeto Final

version: '3.8'

services:
  # API de Predição
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs
      - ./models:/app/models
    environment:
      - PYTHONPATH=/app
      - MODEL_PATH=/app/modelo_manutencao_preditiva.pkl
      - SCALER_PATH=/app/scaler_features.pkl
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - manutencao-network

  # Dashboard Streamlit
  dashboard:
    build: .
    command: streamlit run dashboard.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - manutencao-network

  # Redis para Cache (opcional)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - manutencao-network

  # Nginx como Proxy Reverso (opcional)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - api
      - dashboard
    restart: unless-stopped
    networks:
      - manutencao-network

volumes:
  redis_data:

networks:
  manutencao-network:
    driver: bridge
